### ISSUE TITLE
not the smartest question

### ISSUE THREAD

**Issue by mateo24xx** [jaredhaight/Invoke-MetasploitPayload#2]
you do very good job....
i have just a question sorry if it's a little bit stupid..
where do i put this  script in powershell ..is it with import -module command or in metasploit-framework or something else?
THANK YOU

**Comment by jaredhaight** [comment]
Not a stupid question, usage is covered [here](https://github.com/jaredhaight/Invoke-MetasploitPayload#using-invoke-metasploitpayloadps1).
